"""
Find the Difference (Easy)
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
"""

class Solution1(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        hash_set = {}
        for char in s:
            if char not in hash_set:
                hash_set[char] = 1
            else:
                hash_set[char] += 1
        for char in t:
            if char not in hash_set:
                return char
            hash_set[char] -= 1
            if hash_set[char] == 0:
                del hash_set[char]

class Solution(object):
    def findTheDifference(self, s, t):
        """
        :type s: str
        :type t: str
        :rtype: str
        """
        for char in t:
        	if char not in s or t.count(char) > s.count(char):
        		return char

 


print Solution().findTheDifference("abcd", "abcde")
print Solution().findTheDifference("a", "aa")

print Solution1().findTheDifference("abcd", "abcde")
print Solution1().findTheDifference("a", "aa")